@startuml
title Defguard architecture - context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
Person(user, "User", "Defguard user")
Person(admin, "Administrator", "Manages users and network have access to network overview and network usage by user")
System(web, "Defguard", "Allows interacting with core server and handles all functionality")
System(mfa, "MFA login", "Confirm multi-factor authentication using TOTP - Google authenticator, Web3, WebAuthn/FIDO2 ")
System_Ext(wireguard, "Gateway client", "Provides VPN functionality")
System_Ext(ldap, "LDAP server", "Provides LDAP sync functionality")
System(yubibridge, "YubiBridge", "Provides YubiKey provision functionality")
SystemDb(database, "PostgreSQL")

Rel(admin, web, "Uses", "HTTPS", $tags="firewall")
Rel(admin, mfa, "Uses", "HTTPS", $tags="firewall")
Rel(user, web, "Uses", "HTTPS", $tags="firewall")
Rel(user, mfa, "Uses", "HTTPS", $tags="firewall")
Rel(web, ldap, "Uses", "HTTPS", "Authenticate using current session user and manage data")
Rel(web, wireguard, "Uses", "GRPC", "Authenticate using JWT")
Rel(web, mfa, "Uses", "REST", "") 
Rel(web, database, "Uses", "SQL")
Rel(yubibridge, web, "Uses", "GRPC", "Authenticate using JWT and fetch job with user data")
@enduml
